src/Entity/Tache.php
<?php

namespace App\Entity;

use App\Controller\TacheController;
use App\Repository\TacheRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use ApiPlatform\Core\Annotation\ApiResource;
use Symfony\Component\Validator\Constraints as Assert;


#[ORM\Entity(repositoryClass: TacheRepository::class)]
#[ApiResource]
class Tache
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
     private ?int $id = null;

    #[ORM\Column(length: 20)]
    private ?string $nom = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\NotBlank(
        message: "Veuillez renseigner ce champ "
    )]
    private ?string $description = null;

    #[ORM\Column(length: 10)]
    private ?string $background_color = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $debut = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]

    private ?\DateTimeInterface $fin = null;

    #[ORM\Column]
    private ?bool $ToutelaJournee = null;

    #[ORM\ManyToOne(inversedBy: 'taches')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user_id = null;

    #[ORM\ManyToOne(inversedBy: 'taches')]
    private ?Categorie $Category = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }


    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }


    public function getBackgroundColor(): ?string
    {
        return $this->background_color;
    }

    /**
     * @return bool|null
     */
    public function getToutelaJournee(): ?bool
    {
        return $this->ToutelaJournee;
    }

    public function setBackgroundColor(string $background_color): static
    {
        $this->background_color = $background_color;

        return $this;
    }

    public function getDebut(): ?\DateTimeInterface
    {
        return $this->debut;
    }

    public function setDebut(\DateTimeInterface $debut): static
    {
        $this->debut = $debut;

        return $this;
    }

    public function getFin(): ?\DateTimeInterface
    {
        return $this->fin;
    }

    public function setFin(\DateTimeInterface $fin): static
    {
        $this->fin = $fin;

        return $this;
    }

    public function isToutelaJournee(): ?bool
    {
        return $this->ToutelaJournee;
    }

    public function setToutelaJournee(bool $ToutelaJournee): static
    {
        $this->ToutelaJournee = $ToutelaJournee;

        return $this;
    }

    public function getUserId(): ?User
    {
        return $this->user_id;
    }

    public function setUserId(?User $user_id): static
    {
        $this->user_id = $user_id;

        return $this;
    }

    public function getCategory(): ?Categorie
    {
        return $this->Category;
    }

    public function setCategory(?Categorie $Category): static
    {
        $this->Category = $Category;

        return $this;
    }
}

src/Form/TacheType.php
<?php

namespace App\Form;

use App\Entity\Categorie;
use App\Entity\Tache;
use Doctrine\DBAL\Types\BooleanType;
use Doctrine\DBAL\Types\StringType;
use phpDocumentor\Reflection\PseudoTypes\False_;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ColorType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TacheType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom',TextType::class,array('attr'=>['class'=>'form-control','placeholder'=>'Nom de la tâche']))
            ->add('debut',DateTimeType::class,  [
                'widget' => 'single_text',
                'attr' => [
                    'class' => 'form-control',
                    'max' => date('Y-m-d') ]])
            ->add('fin',DateTimeType::class,  [
                'widget' => 'single_text',
                'attr' => [
                    'class' => 'form-control',
                    'max' => date('Y-m-d') ]])
            ->add('description',TextType::class,array('attr'=>['class'=>'form-control']))
            ->add('background_color',ColorType::class,['attr'=>['class'=>'form-control'],'label'=>'Couleur de la tâche'])
            ->add('Category',EntityType::class,['class'=>Categorie::class,'label'=>'nom de la catégorie','attr'=>['class'=>'form-control']]);
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Tache::class,
        ]);
    }
}

src/Controller/TacheController.php
<?php

namespace App\Controller;

use App\Entity\Tache;
use App\Form\TacheType;
use App\Repository\TacheRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/tache')]
class TacheController extends AbstractController
{
    #[Route('/', name: 'app_tache_index', methods: ['GET'])]
    public function index(TacheRepository $tacheRepository): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        $user= $this->getUser();

        return $this->render('tache/index.html.twig', [
            'taches' => $tacheRepository->findByUser($user),
        ]);
    }

    #[Route('/new', name: 'app_tache_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        $tache = new Tache();
        $form = $this->createForm(TacheType::class, $tache);
        $form->handleRequest($request);
        $user= $this->getUser();
        //dd($user);
        if ($form->isSubmitted() && $form->isValid()) {
            $tache->setUserId($user);
            $entityManager->persist($tache);
            $entityManager->flush();

            return $this->redirectToRoute('app_tache_index', [], Response::HTTP_SEE_OTHER);
        }
        //echo $form->get('description')->getData();

        return $this->render('tache/new.html.twig', [
            'tache' => $tache,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_tache_show', methods: ['GET'])]
    public function show(Tache $tache): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        //echo $tache->getDescription();

        return $this->render('tache/show.html.twig', [
            'tache' => $tache,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_tache_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Tache $tache, EntityManagerInterface $entityManager): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        $form = $this->createForm(TacheType::class, $tache);
        $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_tache_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('tache/edit.html.twig', [
            'tache' => $tache,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_tache_delete', methods: ['POST'])]
    public function delete(Request $request, Tache $tache, EntityManagerInterface $entityManager): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        if ($this->isCsrfTokenValid('delete'.$tache->getId(), $request->request->get('_token'))) {
            $entityManager->remove($tache);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_tache_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/tache/_delete_form.html.twig
<form method="post" action="{{ path('app_tache_delete', {'id': tache.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ tache.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/tache/_form.html.twig
<div class="container mt-5">
{{ form_start(form) }}
    {{ form_widget(form) }}
<br>
    <button class="btn btn-outline-success">{{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}
</div>

templates/tache/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Tache{% endblock %}

{% block body %}
    <div class="container mt-5">
    <h1>Editer une tache</h1>

    {{ include('tache/_form.html.twig', {'button_label': 'Mettre à jour'}) }}

    <a href="{{ path('app_tache_index') }}">back to list</a>

    {{ include('tache/_delete_form.html.twig') }}
    </div>
{% endblock %}

templates/tache/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tache index{% endblock %}

{% block body %}
    <h1>Mes Taches</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Debut</th>
                <th>Fin</th>
                <th>Description</th>
                <th>Couleur de la tache</th>
                <th>Catégorie de la tache </th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for tache in taches %}
            <tr>
                <td>{{ tache.id }}</td>
                <td>{{ tache.nom }}</td>
                <td>{{ tache.debut ? tache.debut|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ tache.fin ? tache.fin|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ tache.description }}</td>
                <td>{{ tache.backgroundColor }}</td>
                <td>{{ tache.category.nom ?? '' }}</td>

                <td>
                    <a href="{{ path('app_tache_show', {'id': tache.id}) }}" class="btn btn-warning">show</a>
                    <a href="{{ path('app_tache_edit', {'id': tache.id}) }}" class="btn btn-light">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_tache_new') }}" class="btn btn-outline-primary">Create new</a>
{% endblock %}

templates/tache/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Tache{% endblock %}

{% block body %}
    <div class="container mt-5">
    <h1>Créer une nouvelle tache</h1>

    {{ include('tache/_form.html.twig') }}

    <a href="{{ path('app_tache_index') }}">back to list</a>
    </div>
{% endblock %}

templates/tache/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tache{% endblock %}

{% block body %}
    <h1>Tache</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ tache.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ tache.nom }}</td>
            </tr>
            <tr>
                <th>Debut</th>
                <td>{{ tache.debut ? tache.debut|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Fin</th>
                <td>{{ tache.fin ? tache.fin|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ tache.description }}</td>
            </tr>
            <tr>
                <th>Background_color</th>
                <td>{{ tache.backgroundColor }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_tache_index') }}">back to list</a>

    <a href="{{ path('app_tache_edit', {'id': tache.id}) }}" class="btn btn-light">edit</a>

    {{ include('tache/_delete_form.html.twig') }}
{% endblock %}